openapi: 3.0.0
info:
  title: AnyTicket Events API
  version: 1.0.0
  description: API to get available events and detailed event information for the AnyTicket ticket selling system
paths:
  /available_events:
    get:
      summary: Get available events for a given date and city
      description: Returns a list of available events for a specified date and city. Use this to find events happening in a specific location on a specific date.
      operationId: getAvailableEvents
      parameters:
        - name: date
          in: query
          description: Date for which to retrieve events (YYYY-MM-DD)
          required: true
          schema:
            type: string
        - name: city
          in: query
          description: City for which to retrieve events
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
                      properties:
                        event:
                          type: string
                          description: Name of the event
                        date:
                          type: string
                          description: Date of the event (YYYY-MM-DD)
                        city:
                          type: string
                          description: City where the event takes place
  /event_details:
    get:
      summary: Get detailed information about a specific event
      description: Returns detailed information about a specific event including ticket price, availability, seats remaining, and age classification. Use this to get more details after finding an event of interest.
      operationId: getEventDetails
      parameters:
        - name: event
          in: query
          description: Name of the event (e.g., Rock Concert, Jazz Festival)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  event_details:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of the event
                      price:
                        type: string
                        description: Ticket price (e.g., $75.00)
                      availability:
                        type: string
                        description: Ticket availability status (available, unavailable)
                      seats_remaining:
                        type: string
                        description: Indication of remaining seats (many, few, none)
                      age_classification:
                        type: string
                        description: Age classification for the event (e.g., 18+, All ages)
                      date:
                        type: string
                        description: Date of the event (YYYY-MM-DD)
                      city:
                        type: string
                        description: City where the event takes place
                  message:
                    type: string
                    description: Informational message about the event details
